spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/makerhub
    username: Yann
    password: Charlotte2901
    driverClassName: org.postgresql.Driver
    
  jpa:
    show-sql: true
    hibernate: 
      ddl-auto: create
    properties:
      hibernate:
        format-sql: true
